<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\MotorcycleType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotorcycleTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = [
            ['brand_id' => 1, 'name' => 'CBR600'],
            ['brand_id' => 1, 'name' => 'CBR1000'],
            ['brand_id' => 1, 'name' => 'CBR500'],
            ['brand_id' => 1, 'name' => 'CBR300'],
            ['brand_id' => 1, 'name' => 'CBR125'],
            ['brand_id' => 1, 'name' => 'CBR1100XX'],
            ['brand_id' => 1, 'name' => 'CB1000'],
            ['brand_id' => 1, 'name' => 'CB500'],
            ['brand_id' => 1, 'name' => 'CB450'],
            ['brand_id' => 1, 'name' => 'CB350'],
            ['brand_id' => 1, 'name' => 'CB250'],
            ['brand_id' => 1, 'name' => 'CB175'],
            ['brand_id' => 1, 'name' => 'CB160'],
            ['brand_id' => 1, 'name' => 'CB125'],
            ['brand_id' => 1, 'name' => 'CB750'],
            ['brand_id' => 1, 'name' => 'CB900'],
            ['brand_id' => 1, 'name' => 'CB650'],
            ['brand_id' => 1, 'name' => 'CBF1000'],
            ['brand_id' => 1, 'name' => 'CMX250 Rebel'],
            ['brand_id' => 1, 'name' => 'CMX300 Rebel'],
            ['brand_id' => 1, 'name' => 'CMX500 Rebel'],
            ['brand_id' => 1, 'name' => 'VT600 Shadow'],
            ['brand_id' => 1, 'name' => 'VT750 Shadow'],
            ['brand_id' => 1, 'name' => 'VT1100 Shadow'],
            ['brand_id' => 1, 'name' => 'VT1300 Stateline'],
            ['brand_id' => 1, 'name' => 'VFR800 Interceptor'],
            ['brand_id' => 1, 'name' => 'VFR750 Interceptor'],
            ['brand_id' => 1, 'name' => 'VFR800A Interceptor'],
            ['brand_id' => 1, 'name' => 'VTR1000 Super Hawk'],
            ['brand_id' => 1, 'name' => 'VTX1800'],
            ['brand_id' => 1, 'name' => 'VTX1300'],
            ['brand_id' => 1, 'name' => 'GL1000 Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1500 Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800 Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800B Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1500C Valkyrie'],
            ['brand_id' => 1, 'name' => 'GL1500SE Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1500A Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1500I Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800HP Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800HPNA Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800HPNM Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800A Gold Wing'],
            ['brand_id' => 1, 'name' => 'GL1800B Gold Wing'],
            ['brand_id' => 1, 'name' => 'ST1100'],
            ['brand_id' => 1, 'name' => 'ST1300'],
            ['brand_id' => 1, 'name' => 'ST1300P'],
            ['brand_id' => 1, 'name' => 'RVT1000R RC51'],
            ['brand_id' => 1, 'name' => 'RVF750R RC45'],
            ['brand_id' => 1, 'name' => 'PC800 Pacific Coast'],
            ['brand_id' => 1, 'name' => 'Monkey'],
            ['brand_id' => 1, 'name' => 'NC700X'],
            ['brand_id' => 1, 'name' => 'NC750X'],
            ['brand_id' => 1, 'name' => 'CTX700'],
            ['brand_id' => 1, 'name' => 'C125 Super Cub'],
            ['brand_id' => 1, 'name' => 'CL175 Scrambler'],
            ['brand_id' => 1, 'name' => 'CL350 Scrambler'],
            ['brand_id' => 1, 'name' => 'CL450 Scrambler'],
            ['brand_id' => 1, 'name' => 'Grom 125'],
            ['brand_id' => 2, 'name' => 'Ninja 250'],
            ['brand_id' => 2, 'name' => 'Ninja 300'],
            ['brand_id' => 2, 'name' => 'Ninja 400'],
            ['brand_id' => 2, 'name' => 'Ninja 500'],
            ['brand_id' => 2, 'name' => 'Ninja 600'],
            ['brand_id' => 2, 'name' => 'Ninja 650'],
            ['brand_id' => 2, 'name' => 'Ninja 750'],
            ['brand_id' => 2, 'name' => 'Ninja 900'],
            ['brand_id' => 2, 'name' => 'Ninja 1000'],
            ['brand_id' => 2, 'name' => 'Ninja 1100'],
            ['brand_id' => 2, 'name' => 'Ninja 1200'],
            ['brand_id' => 2, 'name' => 'Ninja 1400'],
            ['brand_id' => 2, 'name' => 'Ninja H2'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-6'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-7'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-9'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-10'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-12'],
            ['brand_id' => 2, 'name' => 'Ninja ZX-14'],
            ['brand_id' => 2, 'name' => 'EX250F Ninja 250R'],
            ['brand_id' => 2, 'name' => 'Z1000'],
            ['brand_id' => 2, 'name' => 'Z900'],
            ['brand_id' => 2, 'name' => 'Z750'],
            ['brand_id' => 2, 'name' => 'Z250'],
            ['brand_id' => 2, 'name' => 'Z400'],
            ['brand_id' => 2, 'name' => 'Z650'],
            ['brand_id' => 2, 'name' => 'Z900RS'],
            ['brand_id' => 2, 'name' => 'VN500 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN650 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN750 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN800 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN900 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN1500 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN1600 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN1700 Vulcan'],
            ['brand_id' => 2, 'name' => 'VN2000 Vulcan'],
            ['brand_id' => 2, 'name' => 'EN500 Vulcan'],
            ['brand_id' => 2, 'name' => 'EN450 454 LTD'],
            ['brand_id' => 2, 'name' => 'EN650 Vulcan S'],
            ['brand_id' => 2, 'name' => 'KLE300 Versys'],
            ['brand_id' => 2, 'name' => 'KLE650 Versys'],
            ['brand_id' => 2, 'name' => 'ZZR 600'],
            ['brand_id' => 2, 'name' => 'ZRX1200'],
            ['brand_id' => 2, 'name' => 'KLZ1000 Versys SE'],
            ['brand_id' => 2, 'name' => 'H1 Mach III'],
            ['brand_id' => 2, 'name' => 'A1 Samurai'],
            ['brand_id' => 2, 'name' => 'A7 Avenger'],
            ['brand_id' => 2, 'name' => 'BN125 Eliminator'],
            ['brand_id' => 2, 'name' => 'BR125 Z125 PRO'],
            ['brand_id' => 2, 'name' => 'BR250 Z250SL'],
            ['brand_id' => 2, 'name' => 'EJ800 W800'],
            ['brand_id' => 2, 'name' => 'EL250 Eliminator'],
            ['brand_id' => 2, 'name' => 'ZX1100 GPZ'],
            ['brand_id' => 2, 'name' => 'ZN1300 Voyager'],
            ['brand_id' => 3, 'name' => 'R50'],
            ['brand_id' => 3, 'name' => 'R60'],
            ['brand_id' => 3, 'name' => 'R65'],
            ['brand_id' => 3, 'name' => 'R75'],
            ['brand_id' => 3, 'name' => 'R80'],
            ['brand_id' => 3, 'name' => 'R100'],
            ['brand_id' => 3, 'name' => 'R850'],
            ['brand_id' => 3, 'name' => 'R1100'],
            ['brand_id' => 3, 'name' => 'R1150'],
            ['brand_id' => 3, 'name' => 'R1200'],
            ['brand_id' => 3, 'name' => 'R1250'],
            ['brand_id' => 3, 'name' => 'R nine T'],
            ['brand_id' => 3, 'name' => 'K1'],
            ['brand_id' => 3, 'name' => 'K75'],
            ['brand_id' => 3, 'name' => 'K100'],
            ['brand_id' => 3, 'name' => 'K1100'],
            ['brand_id' => 3, 'name' => 'K1200'],
            ['brand_id' => 3, 'name' => 'K1300'],
            ['brand_id' => 3, 'name' => 'K1600'],
            ['brand_id' => 3, 'name' => 'F650'],
            ['brand_id' => 3, 'name' => 'F700GS'],
            ['brand_id' => 3, 'name' => 'F750GS'],
            ['brand_id' => 3, 'name' => 'F800'],
            ['brand_id' => 3, 'name' => 'F850GS'],
            ['brand_id' => 3, 'name' => 'G310'],
            ['brand_id' => 3, 'name' => 'G650GS'],
            ['brand_id' => 3, 'name' => 'S1000R'],
            ['brand_id' => 3, 'name' => 'S1000RR'],
            ['brand_id' => 3, 'name' => 'S1000XR'],
            ['brand_id' => 4, 'name' => 'GSX-R600'],
            ['brand_id' => 4, 'name' => 'GSX-R750'],
            ['brand_id' => 4, 'name' => 'GSX-R1000'],
            ['brand_id' => 4, 'name' => 'GSX-R1100'],
            ['brand_id' => 4, 'name' => 'GSX1300R Hayabusa'],
            ['brand_id' => 4, 'name' => 'GSX600F'],
            ['brand_id' => 4, 'name' => 'GSX750F'],
            ['brand_id' => 4, 'name' => 'GSX1100F'],
            ['brand_id' => 4, 'name' => 'GSX-S1000'],
            ['brand_id' => 4, 'name' => 'GSX-S750'],
            ['brand_id' => 4, 'name' => 'GSX-S750Z'],
            ['brand_id' => 4, 'name' => 'GSX-S1000F'],
            ['brand_id' => 4, 'name' => 'GS500'],
            ['brand_id' => 4, 'name' => 'GS450'],
            ['brand_id' => 4, 'name' => 'GS450L'],
            ['brand_id' => 4, 'name' => 'GS450E'],
            ['brand_id' => 4, 'name' => 'GS450GA'],
            ['brand_id' => 4, 'name' => 'GS450TX'],
            ['brand_id' => 4, 'name' => 'GS550'],
            ['brand_id' => 4, 'name' => 'GS550L'],
            ['brand_id' => 4, 'name' => 'GS650G'],
            ['brand_id' => 4, 'name' => 'GS750'],
            ['brand_id' => 4, 'name' => 'GS850G'],
            ['brand_id' => 4, 'name' => 'GS1000E'],
            ['brand_id' => 4, 'name' => 'GS1100E'],
            ['brand_id' => 4, 'name' => 'GSX1100G'],
            ['brand_id' => 4, 'name' => 'GS1150E'],
            ['brand_id' => 4, 'name' => 'GSF400'],
            ['brand_id' => 4, 'name' => 'GSF600S'],
            ['brand_id' => 4, 'name' => 'GSF1200S'],
            ['brand_id' => 4, 'name' => 'GSF1250S'],
            ['brand_id' => 4, 'name' => 'SV650'],
            ['brand_id' => 4, 'name' => 'SV650S'],
            ['brand_id' => 4, 'name' => 'SV1000'],
            ['brand_id' => 4, 'name' => 'DL650 V-Strom 650'],
            ['brand_id' => 4, 'name' => 'DL1000 V-Strom'],
            ['brand_id' => 4, 'name' => 'DL1050 V-Strom'],
            ['brand_id' => 4, 'name' => 'DL650 V-Strom'],
            ['brand_id' => 4, 'name' => 'TU250X'],
            ['brand_id' => 4, 'name' => 'T500 Titan'],
            ['brand_id' => 4, 'name' => 'TL1000R'],
            ['brand_id' => 4, 'name' => 'TL1000S'],
            ['brand_id' => 4, 'name' => 'RF900'],
            ['brand_id' => 4, 'name' => 'GT185'],
            ['brand_id' => 4, 'name' => 'GT250'],
            ['brand_id' => 4, 'name' => 'GT380'],
            ['brand_id' => 4, 'name' => 'GT550'],
            ['brand_id' => 4, 'name' => 'GT750'],
            ['brand_id' => 4, 'name' => 'GV1400 Cavalcade'],
            ['brand_id' => 4, 'name' => 'M50 Boulevard'],
            ['brand_id' => 4, 'name' => 'M90 Boulevard'],
            ['brand_id' => 4, 'name' => 'C50 Boulevard'],
            ['brand_id' => 4, 'name' => 'C90 Boulevard'],
            ['brand_id' => 4, 'name' => 'S40 Boulevard'],
            ['brand_id' => 4, 'name' => 'S50 Boulevard'],
            ['brand_id' => 4, 'name' => 'S83 Boulevard'],
            ['brand_id' => 4, 'name' => 'VS1400 Intruder'],
            ['brand_id' => 4, 'name' => 'VS800 Intruder'],
            ['brand_id' => 4, 'name' => 'VS750 Intruder'],
            ['brand_id' => 4, 'name' => 'VL1500 Intruder'],
            ['brand_id' => 4, 'name' => 'VL800 Intruder'],
            ['brand_id' => 4, 'name' => 'VZ800 Marauder'],
            ['brand_id' => 4, 'name' => 'VX800'],
            ['brand_id' => 4, 'name' => 'GN125'],
            ['brand_id' => 4, 'name' => 'GN250'],
            ['brand_id' => 4, 'name' => 'GN400'],
            ['brand_id' => 5, 'name' => 'Bonneville'],
            ['brand_id' => 5, 'name' => 'Bonneville T100'],
            ['brand_id' => 5, 'name' => 'Bonneville T120'],
            ['brand_id' => 5, 'name' => 'Bonneville Bobber'],
            ['brand_id' => 5, 'name' => 'Bonneville SE'],
            ['brand_id' => 5, 'name' => 'Bonneville Speedmaster'],
            ['brand_id' => 5, 'name' => 'Street Twin'],
            ['brand_id' => 5, 'name' => 'Street Cup'],
            ['brand_id' => 5, 'name' => 'Street Scrambler'],
            ['brand_id' => 5, 'name' => 'Scrambler'],
            ['brand_id' => 5, 'name' => 'Scrambler 1200'],
            ['brand_id' => 5, 'name' => 'Speed Twin'],
            ['brand_id' => 5, 'name' => 'Speedmaster'],
            ['brand_id' => 5, 'name' => 'Speed Four'],
            ['brand_id' => 5, 'name' => 'Speed Triple'],
            ['brand_id' => 5, 'name' => 'Speed Triple 1200'],
            ['brand_id' => 5, 'name' => 'Street Triple'],
            ['brand_id' => 5, 'name' => 'Street Triple 675'],
            ['brand_id' => 5, 'name' => 'Thruxton'],
            ['brand_id' => 5, 'name' => 'Thruxton 1200'],
            ['brand_id' => 5, 'name' => 'Thruxton RS'],
            ['brand_id' => 5, 'name' => 'Thruxton TFC'],
            ['brand_id' => 5, 'name' => 'Daytona 600'],
            ['brand_id' => 5, 'name' => 'Daytona 675'],
            ['brand_id' => 5, 'name' => 'Daytona 900'],
            ['brand_id' => 5, 'name' => 'Daytona 955i'],
            ['brand_id' => 5, 'name' => 'Daytona 1200'],
            ['brand_id' => 5, 'name' => 'Tiger 800'],
            ['brand_id' => 5, 'name' => 'Tiger 900'],
            ['brand_id' => 5, 'name' => 'Tiger 1050'],
            ['brand_id' => 5, 'name' => 'Tiger 1200'],
            ['brand_id' => 5, 'name' => 'Tiger Explorer'],
            ['brand_id' => 5, 'name' => 'Sprint'],
            ['brand_id' => 5, 'name' => 'Sprint ST'],
            ['brand_id' => 5, 'name' => 'Sprint GT'],
            ['brand_id' => 5, 'name' => 'Trophy 900'],
            ['brand_id' => 5, 'name' => 'Trophy 1200'],
            ['brand_id' => 5, 'name' => 'Trophy SE'],
            ['brand_id' => 5, 'name' => 'Rocket III'],
            ['brand_id' => 5, 'name' => 'Rocket 3'],
            ['brand_id' => 5, 'name' => 'Trident'],
            ['brand_id' => 5, 'name' => 'Thunderbird'],
            ['brand_id' => 5, 'name' => 'Thunderbird 1700'],
            ['brand_id' => 5, 'name' => 'America'],
            ['brand_id' => 5, 'name' => 'America LT'],
            ['brand_id' => 5, 'name' => 'Legend TT'],
            ['brand_id' => 5, 'name' => 'Adventurer'],
            ['brand_id' => 5, 'name' => 'LF Harris Bonneville'],
            ['brand_id' => 6, 'name' => 'Pulsar N125'],
            ['brand_id' => 6, 'name' => 'Pulsar LS125'],
            ['brand_id' => 6, 'name' => 'Pulsar N160'],
            ['brand_id' => 6, 'name' => 'Pulsar N250'],
            ['brand_id' => 6, 'name' => 'Pulsar NS400'],
            ['brand_id' => 6, 'name' => 'Pulsar NS200'],
            ['brand_id' => 6, 'name' => 'Pulsar NS160'],
            ['brand_id' => 6, 'name' => 'Pulsar RS200'],
            ['brand_id' => 6, 'name' => 'Pulsar RS200'],
            ['brand_id' => 6, 'name' => 'Dominar 250'],
            ['brand_id' => 6, 'name' => 'Avenger 220'],
            ['brand_id' => 6, 'name' => 'Pulsar NS125'],
            ['brand_id' => 7, 'name' => 'YZF-R1'],
            ['brand_id' => 7, 'name' => 'YZF-R6'],
            ['brand_id' => 7, 'name' => 'YZF-R3'],
            ['brand_id' => 7, 'name' => 'YZF-R7'],
            ['brand_id' => 7, 'name' => 'YZF600R'],
            ['brand_id' => 7, 'name' => 'YZF750R'],
            ['brand_id' => 7, 'name' => 'VMX1200 V-Max'],
            ['brand_id' => 7, 'name' => 'VMX1700 V-Max'],
            ['brand_id' => 7, 'name' => 'FJR1300'],
            ['brand_id' => 7, 'name' => 'FZR600R'],
            ['brand_id' => 7, 'name' => 'FZR1000'],
            ['brand_id' => 7, 'name' => 'FZ6R'],
            ['brand_id' => 7, 'name' => 'FZS600 FZ6'],
            ['brand_id' => 7, 'name' => 'FZS1000 FZ1'],
            ['brand_id' => 7, 'name' => 'FZ750'],
            ['brand_id' => 7, 'name' => 'FZ8'],
            ['brand_id' => 7, 'name' => 'FZ-07'],
            ['brand_id' => 7, 'name' => 'FZ-09'],
            ['brand_id' => 7, 'name' => 'XSR700'],
            ['brand_id' => 7, 'name' => 'XSR900'],
            ['brand_id' => 7, 'name' => 'XJ600S Seca II'],
            ['brand_id' => 7, 'name' => 'XJ650 Maxim'],
            ['brand_id' => 7, 'name' => 'XS400'],
            ['brand_id' => 7, 'name' => 'XS500'],
            ['brand_id' => 7, 'name' => 'XS650'],
            ['brand_id' => 7, 'name' => 'XS1100'],
            ['brand_id' => 7, 'name' => 'XTZ07 Tenere 700'],
            ['brand_id' => 7, 'name' => 'XTZ1200 Super Tenere'],
            ['brand_id' => 7, 'name' => 'TZ250'],
            ['brand_id' => 7, 'name' => 'TZ350'],
            ['brand_id' => 7, 'name' => 'XV250 Virago'],
            ['brand_id' => 7, 'name' => 'XV535 Virago'],
            ['brand_id' => 7, 'name' => 'XV700 Virago'],
            ['brand_id' => 7, 'name' => 'XV750 Virago'],
            ['brand_id' => 7, 'name' => 'XV1600 Road Star'],
            ['brand_id' => 7, 'name' => 'XV1700 Road Star'],
            ['brand_id' => 7, 'name' => 'XV1900 Roadliner'],
            ['brand_id' => 7, 'name' => 'XVS650 V Star'],
            ['brand_id' => 7, 'name' => 'XVS950 V Star'],
            ['brand_id' => 7, 'name' => 'XVS1100 V Star'],
            ['brand_id' => 7, 'name' => 'XVS1300 V Star'],
            ['brand_id' => 7, 'name' => 'XVS13 Stryker'],
            ['brand_id' => 7, 'name' => 'XVZ1300 Royal Star'],
            ['brand_id' => 7, 'name' => 'YSR50'],
            ['brand_id' => 7, 'name' => 'YX600 Radian'],
            ['brand_id' => 7, 'name' => 'R5'],
            ['brand_id' => 7, 'name' => 'RD200'],
            ['brand_id' => 7, 'name' => 'RD250'],
            ['brand_id' => 7, 'name' => 'RD400'],
            ['brand_id' => 7, 'name' => 'SR400'],
            ['brand_id' => 7, 'name' => 'SR500'],
            ['brand_id' => 8, 'name' => 'Diavel'],
            ['brand_id' => 8, 'name' => 'Monster 1200'],
            ['brand_id' => 8, 'name' => 'Monster 821'],
            ['brand_id' => 8, 'name' => 'Monster 750'],
            ['brand_id' => 8, 'name' => 'Monster 900'],
            ['brand_id' => 8, 'name' => 'Monster 600'],
            ['brand_id' => 8, 'name' => 'Monster 400'],
            ['brand_id' => 8, 'name' => 'Multistrada 1200'],
            ['brand_id' => 8, 'name' => 'Multistrada 950'],
            ['brand_id' => 8, 'name' => 'Multistrada 1260'],
            ['brand_id' => 8, 'name' => 'Panigale V4'],
            ['brand_id' => 8, 'name' => 'Panigale 1199'],
            ['brand_id' => 8, 'name' => 'Panigale 1299'],
            ['brand_id' => 8, 'name' => 'Panigale 959'],
            ['brand_id' => 8, 'name' => 'Panigale 1198'],
            ['brand_id' => 8, 'name' => 'Panigale 999'],
            ['brand_id' => 8, 'name' => 'Panigale 998'],
            ['brand_id' => 8, 'name' => '748'],
            ['brand_id' => 8, 'name' => '749'],
            ['brand_id' => 8, 'name' => '748S'],
            ['brand_id' => 8, 'name' => '748R'],
            ['brand_id' => 8, 'name' => '848'],
            ['brand_id' => 8, 'name' => '996'],
            ['brand_id' => 8, 'name' => '998'],
            ['brand_id' => 8, 'name' => '999R'],
            ['brand_id' => 8, 'name' => '999S'],
            ['brand_id' => 8, 'name' => 'Hypermotard 950'],
            ['brand_id' => 8, 'name' => 'Hypermotard 796'],
            ['brand_id' => 8, 'name' => 'Hypermotard 939'],
            ['brand_id' => 8, 'name' => 'Hyperstrada'],
            ['brand_id' => 8, 'name' => 'GT1000'],
            ['brand_id' => 8, 'name' => 'MH900e'],
            ['brand_id' => 8, 'name' => 'Scrambler 1100'],
            ['brand_id' => 8, 'name' => 'Scrambler 1200'],
            ['brand_id' => 8, 'name' => 'Scrambler Icon'],
            ['brand_id' => 8, 'name' => 'XDiavel'],
            ['brand_id' => 8, 'name' => 'ST2'],
            ['brand_id' => 8, 'name' => 'ST3'],
            ['brand_id' => 8, 'name' => 'ST4'],
            ['brand_id' => 8, 'name' => 'Super Sport'],
            ['brand_id' => 9, 'name' => '200 Duke'],
            ['brand_id' => 9, 'name' => '390 Duke'],
            ['brand_id' => 9, 'name' => '400 Duke'],
            ['brand_id' => 9, 'name' => '620 Duke'],
            ['brand_id' => 9, 'name' => '640 Duke'],
            ['brand_id' => 9, 'name' => '640 Duke II'],
            ['brand_id' => 9, 'name' => '690 Duke'],
            ['brand_id' => 9, 'name' => '790 Duke'],
            ['brand_id' => 9, 'name' => '890 Duke'],
            ['brand_id' => 9, 'name' => '950 Duke'],
            ['brand_id' => 9, 'name' => '990 Super Duke'],
            ['brand_id' => 9, 'name' => '990 Supermoto'],
            ['brand_id' => 9, 'name' => '1190 RC8'],
            ['brand_id' => 10, 'name' => 'F3 675'],
            ['brand_id' => 10, 'name' => 'F3 800'],
            ['brand_id' => 10, 'name' => 'F4 1000'],
            ['brand_id' => 10, 'name' => 'F4 750'],
            ['brand_id' => 10, 'name' => 'F4 312'],
            ['brand_id' => 10, 'name' => 'Brutale 675'],
            ['brand_id' => 10, 'name' => 'Brutale 800'],
            ['brand_id' => 10, 'name' => 'Brutale 910'],
            ['brand_id' => 10, 'name' => 'Brutale 990'],
            ['brand_id' => 10, 'name' => 'Brutale 1000'],
            ['brand_id' => 10, 'name' => 'Brutale 1090'],
            ['brand_id' => 10, 'name' => 'Dragster 800'],
            ['brand_id' => 10, 'name' => 'Rivale 800'],
            ['brand_id' => 10, 'name' => 'Rush 1000'],
            ['brand_id' => 10, 'name' => 'Superveloce 800'],
            ['brand_id' => 10, 'name' => 'Turismo Veloce 800'],
        ];

        DB::table('motorcycle_types')->insert($models);
    }
}
