services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro,z
      - laravel-public-assets:/var/www/public/build:ro,z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(\"${APP_URL_HOST}\")"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls=true"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=cloudflare"
    networks:
      - laravel-production
      - proxy
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build:z
      - laravel-storage-production:/var/www/storage:z
      - ./docker/common/php-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini:Z
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.9.4
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      LANG: C.UTF-8
    volumes:
      - mariadb-data-production:/var/lib/mysql/:Z
      - ./docker/common/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:Z
    networks:
      - laravel-production
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p${DB_PASSWORD} > /dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  laravel-production:
  proxy:
    external: true

volumes:
  mariadb-data-production:
  laravel-storage-production:
  laravel-public-assets:
