services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${DOCKER_WEB_PORT:-80}:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - laravel-development
    depends_on:
      mariadb:
        condition: service_started

  workspace:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - laravel-development

  mariadb:
    image: mariadb:10.9.4
    restart: unless-stopped
    tty: true
    ports:
      - '${DOCKER_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      LANG: C.UTF-8
    volumes:
      - mariadb-data-development:/var/lib/mysql/:Z
      - ./docker/common/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:Z
    networks:
      - laravel-development

networks:
  laravel-development:

volumes:
  mariadb-data-development:
