name: Setup Laravel Environment
description: Install the dependencies for a laravel project

inputs:
  php-version:
    description: 'PHP version to install'
    required: false
    default: '8.4'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: gd, pdo, pdo_mysql, mbstring, bcmath, intl, zip, exif, pcntl, soap, xsl, sockets, dom, curl, libxml, zip

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
      shell: bash
