name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/dependencies

      - name: Run Pint
        run: vendor/bin/pint
  static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/dependencies

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=5 --memory-limit=2G
  tests:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.4' ]

    env:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: password

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/dependencies
        with:
          php-version: ${{ matrix.php }}

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Directory permissions
        run: |
          sudo chown -R $USER:$USER storage bootstrap/cache
          chmod -R 775 storage bootstrap/cache

      - name: Execute tests
        env:
          DB_PORT: 3306
        run: vendor/bin/pest --compact
