name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/dependencies

      - name: Run Pint
        run: vendor/bin/pint
  static:
    if: ${{ always() }}

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/dependencies

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=5 --memory-limit=2G
  tests:
    if: ${{ always() }}
    needs: [ lint, static ]

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '8.4' ]

    steps:
      - uses: ./.github/actions/dependencies
        with:
          php-version: ${{ matrix.php }}

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Directory permissions
        run: |
          sudo chown -R $USER:$USER storage bootstrap/cache
          chmod -R 775 storage bootstrap/cache

      - name: Execute tests
        run: vendor/bin/pest --compact --recreate-databases
